#!/usr/bin/env sh
set -eu

out="${1:-wmi_abi_check.c}"

cat >"$out" <<'EOF'
// SPDX-License-Identifier: GPL-2.0
/*
 * Generated by scripts/gen_wmi_abi_check.sh.
 *
 * This file is compiled by Kbuild before the Rust module. It verifies the
 * Linux WMI C layouts that rust/corsair_wmi_kernel/wmi_ffi.rs mirrors by hand.
 */

#include <linux/stddef.h>
#include <linux/types.h>
#include <linux/wmi.h>

#define ALIGN_UP(value, align) (((value) + (align) - 1) & ~((align) - 1))
#define FIELD_ALIGN(type, field) __alignof__(((type *)0)->field)
#define FIELD_SIZE(type, field) sizeof(((type *)0)->field)
#define FIELD_END(type, field) (offsetof(type, field) + FIELD_SIZE(type, field))

static_assert(offsetof(struct wmi_device, dev) == 0);
static_assert(offsetof(struct wmi_device, setable) == sizeof(struct device));
static_assert(offsetof(struct wmi_device, driver_override) ==
	      ALIGN_UP(FIELD_END(struct wmi_device, setable),
		       FIELD_ALIGN(struct wmi_device, driver_override)));

static_assert(offsetof(struct wmi_buffer, length) == 0);
static_assert(offsetof(struct wmi_buffer, data) ==
	      ALIGN_UP(FIELD_END(struct wmi_buffer, length),
		       FIELD_ALIGN(struct wmi_buffer, data)));

static_assert(offsetof(struct wmi_driver, driver) == 0);
static_assert(offsetof(struct wmi_driver, id_table) ==
	      ALIGN_UP(FIELD_END(struct wmi_driver, driver),
		       FIELD_ALIGN(struct wmi_driver, id_table)));
static_assert(offsetof(struct wmi_driver, no_notify_data) ==
	      FIELD_END(struct wmi_driver, id_table));
static_assert(offsetof(struct wmi_driver, no_singleton) ==
	      FIELD_END(struct wmi_driver, no_notify_data));
static_assert(offsetof(struct wmi_driver, probe) ==
	      ALIGN_UP(FIELD_END(struct wmi_driver, no_singleton),
		       FIELD_ALIGN(struct wmi_driver, probe)));
static_assert(offsetof(struct wmi_driver, remove) ==
	      FIELD_END(struct wmi_driver, probe));
static_assert(offsetof(struct wmi_driver, shutdown) ==
	      FIELD_END(struct wmi_driver, remove));
static_assert(offsetof(struct wmi_driver, notify) ==
	      FIELD_END(struct wmi_driver, shutdown));
static_assert(offsetof(struct wmi_driver, notify_new) ==
	      FIELD_END(struct wmi_driver, notify));

EOF
